on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
  job2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dir
      - run: node --versionn: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: ls -l
  job2:
    runs-on: windows-latest
    steps:
      - run: dir
      - run: node --version
