name: test-111
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
  job2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dir
      - run: node --version
